<?php
$z[0]=Array("global","",368,393);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",492,517);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",678,703);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",774,799);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",896,921);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",1096,1121);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",1283,1308);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("global","",1475,1500);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("global","",1608,1633);
$z[8][4]['name']="cfg_cmsurl";

?>